CREATE TABLE TB_EMPRESA(
	EMP_ID INTEGER NOT NULL,
	EMP_RAZAO_SOCIAL VARCHAR (64) NOT NULL,
	EMP_CNPJ VARCHAR (32) NOT NULL UNIQUE,
	EMP_LOGRADOURO VARCHAR (64),
	EMP_MUNICIPIO VARCHAR (64),
	EMP_NUMERO VARCHAR (10),
	EMP_COMPLEMENTO VARCHAR (64),
	EMP_BAIRRO VARCHAR (64),
	EMP_CEP VARCHAR (16),
	EMP_TELEFONE VARCHAR (32),
	EMP_EMAIL VARCHAR (254) NOT NULL,
	EMP_SITE VARCHAR (254),
	EMP_USUARIO VARCHAR (20) NOT NULL UNIQUE,
	EMP_SENHA VARCHAR (128),
	EMP_CREATED_AT TIMESTAMP NOT NULL,
	EMP_UPDATED_AT TIMESTAMP NOT NULL,
	CONSTRAINT PK_EMP_ID PRIMARY KEY (EMP_ID)
);

CREATE TABLE TB_LEILAO(
	LEI_ID INTEGER NOT NULL,
	LEI_CODIGO INTEGER,
	LEI_DESCRICAO VARCHAR (60) NOT NULL,
	LEI_VENDEDOR INTEGER  NOT NULL,
	LEI_INICIO_PREVISTO TIMESTAMP NOT NULL,
	LEI_CREATED_AT TIMESTAMP NOT NULL,
	LEI_UPDATED_AT TIMESTAMP NOT NULL,
	CONSTRAINT PK_LEI_ID PRIMARY KEY (LEI_ID) 
);

CREATE TABLE TB_COMPRADOR(
	COM_EMP_ID INTEGER NOT NULL,
	COM_LEI_ID INTEGER NOT NULL,
	CONSTRAINT FK_COM_EMP_ID FOREIGN KEY (COM_EMP_ID) REFERENCES TB_EMPRESA (EMP_ID),
	CONSTRAINT FK_COM_LEI_ID FOREIGN KEY (COM_LEI_ID) REFERENCES TB_LEILAO (LEI_ID),
	CONSTRAINT PK_COMPRADOR PRIMARY KEY (COM_EMP_ID, COM_LEI_ID)
);

CREATE TABLE TB_LOTE(
	LOT_ID INTEGER NOT NULL,
	LOT_NUMERO_LOTE INTEGER,
	LOT_DESCRICAO VARCHAR (60) NOT NULL,
	LOT_QUANTIDADE NUMERIC NOT NULL,
	LOT_VALOR_INICIAL NUMERIC,
	LOT_UNIDADE VARCHAR (128) NOT NULL,
	LOT_LEI_ID INTEGER NOT NULL,
	LOT_CREATED_AT TIMESTAMP NOT NULL,
	LOT_UPDATED_AT TIMESTAMP NOT NULL,
	CONSTRAINT PK_LOT_ID PRIMARY KEY (LOT_ID),
	CONSTRAINT FK_LOT_LEI_ID FOREIGN KEY (LOT_LEI_ID) REFERENCES TB_LEILAO (LEI_ID)	 
);

CREATE TABLE TB_UNIDADE(
	UNI_ID INTEGER NOT NULL,
	UNI_NOME VARCHAR (128) NOT NULL,
	UNI_CREATED_AT TIMESTAMP NOT NULL,
	UNI_UPDATED_AT TIMESTAMP NOT NULL,
	CONSTRAINT PK_UNI_ID PRIMARY KEY (UNI_ID)
);

--SEQUENCE DA TABELA EMPRESA
CREATE SEQUENCE IF NOT EXISTS EMPRESA_SEQ
	INCREMENT 1
	MINVALUE 1
	MAXVALUE 999999999
	START 1
	CACHE 1
	OWNED BY TB_EMPRESA.EMP_ID;

--SEQUENCE DA TABELA LEILAO
CREATE SEQUENCE IF NOT EXISTS LEILAO_SEQ
	INCREMENT 1
	MINVALUE 1
	MAXVALUE 999999999
	START 1
	CACHE 1
	OWNED BY TB_LEILAO.LEI_ID; 

--SEQUENCE DA TABELA LOTE
CREATE SEQUENCE IF NOT EXISTS LOTE_SEQ
	INCREMENT 1
	MINVALUE 1
	MAXVALUE 999999999
	START 1
	CACHE 1
	OWNED BY TB_LOTE.LOT_ID;

--SEQUENCE DA TABELA UNIDADE
CREATE SEQUENCE IF NOT EXISTS UNIDADE_SEQ
	INCREMENT 1
	MINVALUE 1
	MAXVALUE 999999999
	START 1
	CACHE 1
	OWNED BY TB_UNIDADE.UNI_ID;


--INSERTS DA TABELA EMPRESA
INSERT INTO TB_EMPRESA (EMP_ID, EMP_RAZAO_SOCIAL, EMP_CNPJ, EMP_LOGRADOURO, EMP_MUNICIPIO, EMP_NUMERO, EMP_COMPLEMENTO,
                        EMP_BAIRRO, EMP_CEP, EMP_TELEFONE, EMP_EMAIL, EMP_SITE, EMP_USUARIO, EMP_SENHA, EMP_CREATED_AT, EMP_UPDATED_AT) VALUES (NEXTVAL('EMPRESA_SEQ'), 'Itaú Unibanco Banco Múltiplo S.A. (Banco Itaú)', '81330922000169', 'RUA 1', 'COXIM', '1', 'PERTO DO CENTRO', 'FLÁVIO GARCIA',
                                                                                                                                                '79400000', '12345678', 'itau@gmail.com', 'WWW.ITAU.COM', 'ITAU', 'ITAU123', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO TB_EMPRESA (EMP_ID, EMP_RAZAO_SOCIAL, EMP_CNPJ, EMP_LOGRADOURO, EMP_MUNICIPIO, EMP_NUMERO, EMP_COMPLEMENTO,
                        EMP_BAIRRO, EMP_CEP, EMP_TELEFONE, EMP_EMAIL, EMP_SITE, EMP_USUARIO, EMP_SENHA, EMP_CREATED_AT, EMP_UPDATED_AT) VALUES (NEXTVAL('EMPRESA_SEQ'), 'Coca-Cola Indústrias Ltda. (Coca-Cola)', '98321538000100', 'RUA 1', 'COXIM', '1', 'PERTO DO CENTRO', 'FLÁVIO GARCIA',
                                                                                                                                                '79400000', '12345678', 'cocacola@gmail.com', 'WWW.COCACOLA.COM', 'COCACOLA', 'COCACOLA123', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO TB_EMPRESA (EMP_ID, EMP_RAZAO_SOCIAL, EMP_CNPJ, EMP_LOGRADOURO, EMP_MUNICIPIO, EMP_NUMERO, EMP_COMPLEMENTO,
                        EMP_BAIRRO, EMP_CEP, EMP_TELEFONE, EMP_EMAIL, EMP_SITE, EMP_USUARIO, EMP_SENHA, EMP_CREATED_AT, EMP_UPDATED_AT) VALUES (NEXTVAL('EMPRESA_SEQ'), 'Telefônica Brasil S.A. (Vivo)', '20392146000137', 'RUA 1', 'COXIM', '1', 'PERTO DO CENTRO', 'FLÁVIO GARCIA',
                                                                                                                                                '79400000', '12345678', 'vivo@gmail.com', 'WWW.VIVO.COM', 'VIVO', 'VIVO123', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO TB_EMPRESA (EMP_ID, EMP_RAZAO_SOCIAL, EMP_CNPJ, EMP_LOGRADOURO, EMP_MUNICIPIO, EMP_NUMERO, EMP_COMPLEMENTO,
                        EMP_BAIRRO, EMP_CEP, EMP_TELEFONE, EMP_EMAIL, EMP_SITE, EMP_USUARIO, EMP_SENHA, EMP_CREATED_AT, EMP_UPDATED_AT) VALUES (NEXTVAL('EMPRESA_SEQ'), 'ContaAzul Software Ltda. (ContaAzul)', '97124523000181', 'RUA 1', 'COXIM', '1', 'PERTO DO CENTRO', 'FLÁVIO GARCIA',
                                                                                                                                                '79400000', '12345678', 'contaazul@gmail.com', 'WWW.CONTAAZUL.COM', 'CONTAAZUL', 'CONTAAZUL123', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO TB_EMPRESA (EMP_ID, EMP_RAZAO_SOCIAL, EMP_CNPJ, EMP_LOGRADOURO, EMP_MUNICIPIO, EMP_NUMERO, EMP_COMPLEMENTO,
                        EMP_BAIRRO, EMP_CEP, EMP_TELEFONE, EMP_EMAIL, EMP_SITE, EMP_USUARIO, EMP_SENHA, EMP_CREATED_AT, EMP_UPDATED_AT) VALUES (NEXTVAL('EMPRESA_SEQ'), 'Magnetis Consultoria de Investimentos Ltda. (Magnetis)', '63730938000187', 'RUA 1', 'COXIM', '1', 'PERTO DO CENTRO', 'FLÁVIO GARCIA',
                                                                                                                                                '79400000', '12345678', 'magnetis@gmail.com', 'WWW.MAGNETIS.COM', 'MAGNETIS', 'MAGNETIS123', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO TB_EMPRESA (EMP_ID, EMP_RAZAO_SOCIAL, EMP_CNPJ, EMP_LOGRADOURO, EMP_MUNICIPIO, EMP_NUMERO, EMP_COMPLEMENTO,
                        EMP_BAIRRO, EMP_CEP, EMP_TELEFONE, EMP_EMAIL, EMP_SITE, EMP_USUARIO, EMP_SENHA, EMP_CREATED_AT, EMP_UPDATED_AT) VALUES (NEXTVAL('EMPRESA_SEQ'), 'MSS Panificadora Ltda. EPP.', '48026145000198', 'RUA 1', 'COXIM', '1', 'PERTO DO CENTRO', 'FLÁVIO GARCIA',
                                                                                                                                                '79400000', '12345678', 'mss@gmail.com', 'WWW.MSS.COM', 'MSS', 'MSS123', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO TB_EMPRESA (EMP_ID, EMP_RAZAO_SOCIAL, EMP_CNPJ, EMP_LOGRADOURO, EMP_MUNICIPIO, EMP_NUMERO, EMP_COMPLEMENTO,
                        EMP_BAIRRO, EMP_CEP, EMP_TELEFONE, EMP_EMAIL, EMP_SITE, EMP_USUARIO, EMP_SENHA, EMP_CREATED_AT, EMP_UPDATED_AT) VALUES (NEXTVAL('EMPRESA_SEQ'), 'João Roberto Almeida Alimentação Ltda. ME', '99607750000193', 'RUA 1', 'COXIM', '1', 'PERTO DO CENTRO', 'FLÁVIO GARCIA',
                                                                                                                                                '79400000', '12345678', 'joao@gmail.com', 'WWW.JOAO.COM', 'JOAO', 'JOAO123', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO TB_EMPRESA (EMP_ID, EMP_RAZAO_SOCIAL, EMP_CNPJ, EMP_LOGRADOURO, EMP_MUNICIPIO, EMP_NUMERO, EMP_COMPLEMENTO,
                        EMP_BAIRRO, EMP_CEP, EMP_TELEFONE, EMP_EMAIL, EMP_SITE, EMP_USUARIO, EMP_SENHA, EMP_CREATED_AT, EMP_UPDATED_AT) VALUES (NEXTVAL('EMPRESA_SEQ'), 'Mateus Software Ltda.', '50291032000161', 'RUA 1', 'COXIM', '1', 'PERTO DO CENTRO', 'FLÁVIO GARCIA',
                                                                                                                                                '79400000', '12345678', 'mateus@gmail.com', 'WWW.MATEUS.COM', 'MATEUS', 'MATEUS123', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO TB_EMPRESA (EMP_ID, EMP_RAZAO_SOCIAL, EMP_CNPJ, EMP_LOGRADOURO, EMP_MUNICIPIO, EMP_NUMERO, EMP_COMPLEMENTO,
                        EMP_BAIRRO, EMP_CEP, EMP_TELEFONE, EMP_EMAIL, EMP_SITE, EMP_USUARIO, EMP_SENHA, EMP_CREATED_AT, EMP_UPDATED_AT) VALUES (NEXTVAL('EMPRESA_SEQ'), 'ArtComp sistemas ltda.', '45691139000167', 'RUA 1', 'COXIM', '1', 'PERTO DO CENTRO', 'FLÁVIO GARCIA',
                                                                                                                                                '79400000', '12345678', 'artcomp@gmail.com', 'WWW.ARTCOMP.COM', 'ARTCOMP', 'ARTCOMP123', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO TB_EMPRESA (EMP_ID, EMP_RAZAO_SOCIAL, EMP_CNPJ, EMP_LOGRADOURO, EMP_MUNICIPIO, EMP_NUMERO, EMP_COMPLEMENTO,
                        EMP_BAIRRO, EMP_CEP, EMP_TELEFONE, EMP_EMAIL, EMP_SITE, EMP_USUARIO, EMP_SENHA, EMP_CREATED_AT, EMP_UPDATED_AT) VALUES (NEXTVAL('EMPRESA_SEQ'), 'Integral Médica ltda.', '70287753000105', 'RUA 1', 'COXIM', '1', 'PERTO DO CENTRO', 'FLÁVIO GARCIA',
                                                                                                                                                '79400000', '12345678', 'integralmedica@gmail.com', 'WWW.INTEGRALMEDICA.COM', 'INTEGRALMEDICA', 'INTEGRALMEDICA123', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);


--INSERTS DA TABELA LEILAO
INSERT INTO TB_LEILAO(LEI_ID, LEI_CODIGO, LEI_DESCRICAO, LEI_VENDEDOR, LEI_INICIO_PREVISTO, LEI_CREATED_AT, LEI_UPDATED_AT) VALUES (NEXTVAL('LEILAO_SEQ'), 1, 'LEILÃO 1', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TB_LEILAO(LEI_ID, LEI_CODIGO, LEI_DESCRICAO, LEI_VENDEDOR, LEI_INICIO_PREVISTO, LEI_CREATED_AT, LEI_UPDATED_AT) VALUES (NEXTVAL('LEILAO_SEQ'), 2, 'LEILÃO 2', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TB_LEILAO(LEI_ID, LEI_CODIGO, LEI_DESCRICAO, LEI_VENDEDOR, LEI_INICIO_PREVISTO, LEI_CREATED_AT, LEI_UPDATED_AT) VALUES (NEXTVAL('LEILAO_SEQ'), 3, 'LEILÃO 3', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TB_LEILAO(LEI_ID, LEI_CODIGO, LEI_DESCRICAO, LEI_VENDEDOR, LEI_INICIO_PREVISTO, LEI_CREATED_AT, LEI_UPDATED_AT) VALUES (NEXTVAL('LEILAO_SEQ'), 4, 'LEILÃO 4', 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TB_LEILAO(LEI_ID, LEI_CODIGO, LEI_DESCRICAO, LEI_VENDEDOR, LEI_INICIO_PREVISTO, LEI_CREATED_AT, LEI_UPDATED_AT) VALUES (NEXTVAL('LEILAO_SEQ'), 5, 'LEILÃO 5', 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TB_LEILAO(LEI_ID, LEI_CODIGO, LEI_DESCRICAO, LEI_VENDEDOR, LEI_INICIO_PREVISTO, LEI_CREATED_AT, LEI_UPDATED_AT) VALUES (NEXTVAL('LEILAO_SEQ'), 6, 'LEILÃO 6', 6, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TB_LEILAO(LEI_ID, LEI_CODIGO, LEI_DESCRICAO, LEI_VENDEDOR, LEI_INICIO_PREVISTO, LEI_CREATED_AT, LEI_UPDATED_AT) VALUES (NEXTVAL('LEILAO_SEQ'), 7, 'LEILÃO 7', 7, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TB_LEILAO(LEI_ID, LEI_CODIGO, LEI_DESCRICAO, LEI_VENDEDOR, LEI_INICIO_PREVISTO, LEI_CREATED_AT, LEI_UPDATED_AT) VALUES (NEXTVAL('LEILAO_SEQ'), 8, 'LEILÃO 8', 8, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TB_LEILAO(LEI_ID, LEI_CODIGO, LEI_DESCRICAO, LEI_VENDEDOR, LEI_INICIO_PREVISTO, LEI_CREATED_AT, LEI_UPDATED_AT) VALUES (NEXTVAL('LEILAO_SEQ'), 9, 'LEILÃO 9', 9, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TB_LEILAO(LEI_ID, LEI_CODIGO, LEI_DESCRICAO, LEI_VENDEDOR, LEI_INICIO_PREVISTO, LEI_CREATED_AT, LEI_UPDATED_AT) VALUES (NEXTVAL('LEILAO_SEQ'), 10, 'LEILÃO 10', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);


--INSERTS DA TABELA COMPRADOR
INSERT INTO TB_COMPRADOR (COM_EMP_ID, COM_LEI_ID) VALUES (1, 1);
INSERT INTO TB_COMPRADOR (COM_EMP_ID, COM_LEI_ID) VALUES (2, 2);
INSERT INTO TB_COMPRADOR (COM_EMP_ID, COM_LEI_ID) VALUES (3, 3);
INSERT INTO TB_COMPRADOR (COM_EMP_ID, COM_LEI_ID) VALUES (4, 4);
INSERT INTO TB_COMPRADOR (COM_EMP_ID, COM_LEI_ID) VALUES (5, 5);
INSERT INTO TB_COMPRADOR (COM_EMP_ID, COM_LEI_ID) VALUES (6, 6);
INSERT INTO TB_COMPRADOR (COM_EMP_ID, COM_LEI_ID) VALUES (7, 7);
INSERT INTO TB_COMPRADOR (COM_EMP_ID, COM_LEI_ID) VALUES (8, 8);
INSERT INTO TB_COMPRADOR (COM_EMP_ID, COM_LEI_ID) VALUES (9, 9);
INSERT INTO TB_COMPRADOR (COM_EMP_ID, COM_LEI_ID) VALUES (10, 10);

--INSERTS DA TABELA LOTE
INSERT INTO TB_LOTE (LOT_ID, LOT_NUMERO_LOTE, LOT_DESCRICAO, LOT_QUANTIDADE, LOT_VALOR_INICIAL, LOT_UNIDADE, LOT_LEI_ID, LOT_CREATED_AT, LOT_UPDATED_AT)
VALUES (NEXTVAL('LOTE_SEQ'), 1, 'LOTE 1', 1, 1000, 'UNIDADE 1', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO TB_LOTE (LOT_ID, LOT_NUMERO_LOTE, LOT_DESCRICAO, LOT_QUANTIDADE, LOT_VALOR_INICIAL, LOT_UNIDADE, LOT_LEI_ID, LOT_CREATED_AT, LOT_UPDATED_AT)
VALUES (NEXTVAL('LOTE_SEQ'), 2, 'LOTE 2', 2, 1000, 'UNIDADE 2', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO TB_LOTE (LOT_ID, LOT_NUMERO_LOTE, LOT_DESCRICAO, LOT_QUANTIDADE, LOT_VALOR_INICIAL, LOT_UNIDADE, LOT_LEI_ID, LOT_CREATED_AT, LOT_UPDATED_AT)
VALUES (NEXTVAL('LOTE_SEQ'), 3, 'LOTE 3', 3, 1000, 'UNIDADE 3', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO TB_LOTE (LOT_ID, LOT_NUMERO_LOTE, LOT_DESCRICAO, LOT_QUANTIDADE, LOT_VALOR_INICIAL, LOT_UNIDADE, LOT_LEI_ID, LOT_CREATED_AT, LOT_UPDATED_AT)
VALUES (NEXTVAL('LOTE_SEQ'), 4, 'LOTE 4', 4, 1000, 'UNIDADE 4', 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO TB_LOTE (LOT_ID, LOT_NUMERO_LOTE, LOT_DESCRICAO, LOT_QUANTIDADE, LOT_VALOR_INICIAL, LOT_UNIDADE, LOT_LEI_ID, LOT_CREATED_AT, LOT_UPDATED_AT)
VALUES (NEXTVAL('LOTE_SEQ'), 5, 'LOTE 5', 5, 1000, 'UNIDADE 5', 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO TB_LOTE (LOT_ID, LOT_NUMERO_LOTE, LOT_DESCRICAO, LOT_QUANTIDADE, LOT_VALOR_INICIAL, LOT_UNIDADE, LOT_LEI_ID, LOT_CREATED_AT, LOT_UPDATED_AT)
VALUES (NEXTVAL('LOTE_SEQ'), 6, 'LOTE 6', 6, 1000, 'UNIDADE 6', 6, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO TB_LOTE (LOT_ID, LOT_NUMERO_LOTE, LOT_DESCRICAO, LOT_QUANTIDADE, LOT_VALOR_INICIAL, LOT_UNIDADE, LOT_LEI_ID, LOT_CREATED_AT, LOT_UPDATED_AT)
VALUES (NEXTVAL('LOTE_SEQ'), 7, 'LOTE 7', 8, 1000, 'UNIDADE 7', 7, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO TB_LOTE (LOT_ID, LOT_NUMERO_LOTE, LOT_DESCRICAO, LOT_QUANTIDADE, LOT_VALOR_INICIAL, LOT_UNIDADE, LOT_LEI_ID, LOT_CREATED_AT, LOT_UPDATED_AT)
VALUES (NEXTVAL('LOTE_SEQ'), 8, 'LOTE 8', 8, 1000, 'UNIDADE 8', 8, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO TB_LOTE (LOT_ID, LOT_NUMERO_LOTE, LOT_DESCRICAO, LOT_QUANTIDADE, LOT_VALOR_INICIAL, LOT_UNIDADE, LOT_LEI_ID, LOT_CREATED_AT, LOT_UPDATED_AT)
VALUES (NEXTVAL('LOTE_SEQ'), 9, 'LOTE 9', 9, 1000, 'UNIDADE 9', 9, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO TB_LOTE (LOT_ID, LOT_NUMERO_LOTE, LOT_DESCRICAO, LOT_QUANTIDADE, LOT_VALOR_INICIAL, LOT_UNIDADE, LOT_LEI_ID, LOT_CREATED_AT, LOT_UPDATED_AT)
VALUES (NEXTVAL('LOTE_SEQ'), 10, 'LOTE 10', 10, 1000, 'UNIDADE 10', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

--INSERTS DA TABELA UNIDADE
INSERT INTO TB_UNIDADE (UNI_ID, UNI_NOME, UNI_CREATED_AT, UNI_UPDATED_AT) VALUES (NEXTVAL('UNIDADE_SEQ'), 'UNIDADE 1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TB_UNIDADE (UNI_ID, UNI_NOME, UNI_CREATED_AT, UNI_UPDATED_AT) VALUES (NEXTVAL('UNIDADE_SEQ'), 'UNIDADE 2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TB_UNIDADE (UNI_ID, UNI_NOME, UNI_CREATED_AT, UNI_UPDATED_AT) VALUES (NEXTVAL('UNIDADE_SEQ'), 'UNIDADE 3', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TB_UNIDADE (UNI_ID, UNI_NOME, UNI_CREATED_AT, UNI_UPDATED_AT) VALUES (NEXTVAL('UNIDADE_SEQ'), 'UNIDADE 4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TB_UNIDADE (UNI_ID, UNI_NOME, UNI_CREATED_AT, UNI_UPDATED_AT) VALUES (NEXTVAL('UNIDADE_SEQ'), 'UNIDADE 5', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TB_UNIDADE (UNI_ID, UNI_NOME, UNI_CREATED_AT, UNI_UPDATED_AT) VALUES (NEXTVAL('UNIDADE_SEQ'), 'UNIDADE 6', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TB_UNIDADE (UNI_ID, UNI_NOME, UNI_CREATED_AT, UNI_UPDATED_AT) VALUES (NEXTVAL('UNIDADE_SEQ'), 'UNIDADE 7', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TB_UNIDADE (UNI_ID, UNI_NOME, UNI_CREATED_AT, UNI_UPDATED_AT) VALUES (NEXTVAL('UNIDADE_SEQ'), 'UNIDADE 8', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TB_UNIDADE (UNI_ID, UNI_NOME, UNI_CREATED_AT, UNI_UPDATED_AT) VALUES (NEXTVAL('UNIDADE_SEQ'), 'UNIDADE 9', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TB_UNIDADE (UNI_ID, UNI_NOME, UNI_CREATED_AT, UNI_UPDATED_AT) VALUES (NEXTVAL('UNIDADE_SEQ'), 'UNIDADE 10', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

